#!/bin/bash
#
# Copyright 2012-2016 by Daniel Volk <mail@volkarts.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

_SCRIPT_NAME=`readlink -f "${0}"`
_SCRIPT_PATH=`dirname "${_SCRIPT_NAME}"`

_LIB_PATHS=("${_SCRIPT_PATH}/lib" "/usr/share/prot" "/usr/local/share/prot")

LIBRARY_PATH=
for _LP in "${_LIB_PATHS[@]}"; do
    if [ -e "${_LP}/main.sh" ]; then
        LIBRARY_PATH="${_LP}"
        source "${_LP}/main.sh"
        break
    fi
done

CALLER_CMD=`basename "${0}"`

if [ "${LIBRARY_PATH}" == "" ]; then
    echo "`${CALLER_CMD}` was not properbly installed" >&2
    exit 1
fi

exec_gprot "$@"

# kate space-indent on; indent-width 4; mixed-indent off; indent-mode cstyle;
